apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: machine
  template:
    metadata:
      labels:
        app: machine
    spec:
      containers:
      - name: machine
        image: avnishsingh17/gitops-project:latest
        ports:
        - containerPort: 5000